language: node_js
matrix:
  include:
    - node_js: "11"
    - node_js: "10"
    - node_js: "8"
    - node_js: "6"
    - node_js: "4"
      env: BABEL=true

script: "[[ $BABEL == true ]] && npm run test:babel || npm test"
after_success:
  - npm run travis-coverage
